# Generated by Django 5.2.3 on 2025-06-18 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('audio_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='audio/')),
                ('audio_title', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('transcription_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcription_title', models.CharField(max_length=100)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend_rna.audio')),
            ],
        ),
    ]
